export type Apartment={id:string;slug:string;name:string;type:string;bedrooms:number;bathrooms:number;capacity:number;pricePerNight:number;status:'AVAILABLE'|'MAINTENANCE'|'INACTIVE';description:string;images:string[];amenities:string[]}
export type Booking={id:string;reference:string;apartmentSlug:string;apartmentName:string;checkIn:string;checkOut:string;guests:number;guestName:string;guestEmail:string;guestPhone:string;subtotal:number;cleaningFee:number;serviceFee:number;total:number;bookingStatus:'Pending'|'Confirmed'|'Checked In'|'Completed'|'Cancelled';paymentStatus:'Pending'|'Paid'|'Failed'|'Refunded'}
const names=['Monica','Irene','Sunita','Theresa','Ragnar','Mafia','Caesar','Pablo','Alexa','Rahat']
export const apartments:Apartment[]=names.map((name,i)=>{const bedrooms=i<8?1:2;return{id:name.toLowerCase(),slug:name.toLowerCase(),name,type:`${bedrooms} Bedroom Apartment`,bedrooms,bathrooms:bedrooms,capacity:bedrooms===1?2:4,pricePerNight:bedrooms===1?200000:400000,status:'AVAILABLE',description:`A refined ${bedrooms}-bedroom luxury apartment in Ikota GRA, designed for privacy, comfort and effortless city living.`,images:[`/images/apartments/${name.toLowerCase()}-1.jpg`,`/images/apartments/${name.toLowerCase()}-2.jpg`],amenities:['High-Speed Wi-Fi','Smart 65” TV','Full AC','Kitchen','Housekeeping','24/7 Power Supply']}})
export const demoBookings:Booking[]=[{id:'demo-monica-1215',reference:'RHT-20260912-001',apartmentSlug:'monica',apartmentName:'Monica',checkIn:'2026-09-12',checkOut:'2026-09-15',guests:2,guestName:'Demo Guest',guestEmail:'guest@example.com',guestPhone:'+234 800 000 0000',subtotal:600000,cleaningFee:30000,serviceFee:60000,total:690000,bookingStatus:'Confirmed',paymentStatus:'Paid'},{id:'demo-irene-1618',reference:'RHT-20260916-002',apartmentSlug:'irene',apartmentName:'Irene',checkIn:'2026-09-16',checkOut:'2026-09-18',guests:2,guestName:'Amaka Guest',guestEmail:'amaka@example.com',guestPhone:'+234 800 000 0001',subtotal:400000,cleaningFee:30000,serviceFee:40000,total:470000,bookingStatus:'Confirmed',paymentStatus:'Paid'},{id:'demo-alexa-1923',reference:'RHT-20260919-003',apartmentSlug:'alexa',apartmentName:'Alexa',checkIn:'2026-09-19',checkOut:'2026-09-23',guests:4,guestName:'Chidi Guest',guestEmail:'chidi@example.com',guestPhone:'+234 800 000 0002',subtotal:1600000,cleaningFee:50000,serviceFee:160000,total:1810000,bookingStatus:'Pending',paymentStatus:'Pending'}]
export const blockedDates=[{apartmentSlug:'monica',start:'2026-09-20',end:'2026-09-25',reason:'Maintenance'}]
export function getApartment(slug:string){return apartments.find(a=>a.slug===slug)}
export function nightsBetween(a:string,b:string){return Math.max(1,Math.round((new Date(b).getTime()-new Date(a).getTime())/86400000))}
export function overlaps(start:string,end:string,otherStart:string,otherEnd:string){return new Date(otherStart)<new Date(end)&&new Date(otherEnd)>new Date(start)}
export function isAvailable(slug:string,start:string,end:string){const apt=getApartment(slug);if(!apt||apt.status!=='AVAILABLE')return false;return !demoBookings.filter(b=>b.apartmentSlug===slug&&['Confirmed','Checked In','Pending'].includes(b.bookingStatus)).some(b=>overlaps(start,end,b.checkIn,b.checkOut))&&!blockedDates.filter(b=>b.apartmentSlug===slug).some(b=>overlaps(start,end,b.start,b.end))}
export function formatNaira(n:number){return new Intl.NumberFormat('en-NG',{style:'currency',currency:'NGN',maximumFractionDigits:0}).format(n)}
