BEGIN;
ALTER TABLE "Booking" ADD COLUMN "discountPercent" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Booking" ADD COLUMN "promoCode" TEXT;
CREATE TABLE "PromoCode" (
  "id" TEXT NOT NULL PRIMARY KEY,
  "code" TEXT NOT NULL UNIQUE,
  "percentage" INTEGER NOT NULL CHECK ("percentage" BETWEEN 1 AND 100),
  "active" BOOLEAN NOT NULL DEFAULT true,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP(3) NOT NULL
);
COMMIT;
